async_study/challenges/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.challenges, name="challenges"),
    path("start_challenge/", views.start_challenge, name="start_challenge"),
    path("<int:id>/", views.challenge, name="challenge"),
    path("remove_challenge/<int:id>", views.remove_challenge, name="remove_challenge"),
    path("report/<int:challenge_id>/", views.report, name="report"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="/flashcards/")),
    path("auth/", include("async_study.users.urls")),
    path("flashcards/", include("async_study.flashcards.urls")),
    path("challenges/", include("async_study.challenges.urls")),
    path("booklets/", include("async_study.booklets.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied!")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found!")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns
    if "django_browser_reload" in settings.INSTALLED_APPS:
        urlpatterns = [path("__reload__/", include("django_browser_reload.urls"))] + urlpatterns

async_study/challenges/models.py
from async_study.flashcards.models import Category, Flashcard
from django.contrib.auth.models import User
from django.db import models


class Challenge(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    categories = models.ManyToManyField(Category)
    difficulty = models.CharField(max_length=1, choices=Flashcard.difficulty_choices)
    questions_qt = models.PositiveIntegerField(default=1)
    flashcards = models.ManyToManyField(Flashcard, through="ChallengeFlashcard")

    def is_answered(self):
        return ChallengeFlashcard.objects.filter(challenge=self, is_answered=True).count() == self.questions_qt

    def __str__(self):
        return self.title


class ChallengeFlashcard(models.Model):
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE)
    flashcard = models.ForeignKey(Flashcard, on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)
    is_answered = models.BooleanField(default=False)

    class Meta:
        unique_together = ("challenge", "flashcard")
        verbose_name = "Challenge Flashcard"
        verbose_name_plural = "Challenge Flashcards"
        constraints = [models.UniqueConstraint(fields=["challenge", "flashcard"], name="unique_challenge_flashcard")]

    def __str__(self):
        return f"{self.challenge} - {self.flashcard}"

async_study/challenges/views.py
from async_study.flashcards.models import Category, Flashcard
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from .models import Challenge, ChallengeFlashcard


@login_required(login_url="sign_in")
def challenges(request):
    difficulties = [{"value": d[0], "label": d[1]} for d in Flashcard.difficulty_choices]
    categories = Category.objects.all()
    challenges = Challenge.objects.filter(user=request.user)

    category = request.GET.get("category") or ""
    difficulty = request.GET.get("difficulty") or ""
    status = request.GET.get("status") or ""
    if category:
        challenges = challenges.filter(categories__id=category)
    if difficulty:
        challenges = challenges.filter(difficulty=difficulty)
    if status:
        status = status == "True"
        challenges = [c for c in challenges if c.is_answered() == status]
    return render(
        request,
        "challenges.html",
        {
            "challenges": challenges,
            "categories": categories,
            "difficulties": difficulties,
            "f": {
                "category": category,
                "difficulty": difficulty,
                "status": status,
            },
        },
    )


@login_required(login_url="sign_in")
def start_challenge(request):
    difficulties = [{"value": d[0], "label": d[1]} for d in Flashcard.difficulty_choices]
    categories = Category.objects.all()
    if request.method == "POST":
        title = request.POST.get("title") or ""
        post_categories = request.POST.getlist("categories") or []
        difficulty = request.POST.get("difficulty") or ""
        questions_qt = request.POST.get("questions_qt") or ""
        questions_qt = int(questions_qt) if questions_qt.isdigit() else 0

        if len(title.strip()) == 0 or len(post_categories) == 0 or len(difficulty.strip()) == 0:
            messages.error(request, "All fields are required")
            return redirect("start_challenge")
        if questions_qt < 1:
            messages.error(request, "Invalid number of questions")
            return redirect("start_challenge")
        if True not in [d["value"] == difficulty for d in difficulties]:
            messages.error(request, "Invalid difficulty")
            return redirect("start_challenge")
        post_categories = categories.filter(id__in=post_categories)
        if not post_categories.exists():
            messages.error(request, "Category not found")
            return redirect("start_challenge")

        flashcards = Flashcard.objects.filter(
            user=request.user, category__in=post_categories, difficulty=difficulty
        ).order_by("?")[:questions_qt]
        if not flashcards.exists():
            messages.error(request, "No flashcards found")
            return redirect("start_challenge")
        if flashcards.count() < questions_qt:
            messages.warning(request, "Not enough flashcards found")

        try:
            challenge = Challenge.objects.create(
                user=request.user,
                title=title,
                questions_qt=flashcards.count(),
                difficulty=difficulty,
            )
            for flashcard in flashcards:
                challenge.categories.add(flashcard.category)
                ChallengeFlashcard.objects.create(challenge=challenge, flashcard=flashcard)
        except Exception:
            messages.error(request, "Error creating challenge")
            return redirect("start_challenge")
        messages.success(request, "Challenge created successfully")
        return redirect("challenge", id=challenge.id)
    return render(request, "start_challenge.html", {"categories": categories, "difficulties": difficulties})


@login_required(login_url="sign_in")
def challenge(request, id):
    try:
        challenge = Challenge.objects.get(id=id, user=request.user)
        flashcards = ChallengeFlashcard.objects.filter(challenge=challenge)
        answered_flashcards = flashcards.filter(is_answered=True)
        not_answered_flashcards = flashcards.filter(is_answered=False).count()
        correct = answered_flashcards.filter(is_correct=True).count()
        incorrect = answered_flashcards.filter(is_correct=False).count()
        return render(
            request,
            "challenge.html",
            {
                "challenge": challenge,
                "flashcards": flashcards,
                "correct": correct,
                "incorrect": incorrect,
                "not_answered_flashcards": not_answered_flashcards,
            },
        )
    except Challenge.DoesNotExist:
        messages.error(request, "Challenge not found")
        return redirect("challenges")
    except Exception as e:
        print(e)
        messages.error(request, "Error loading challenge")
        return redirect("challenges")


@login_required(login_url="sign_in")
def remove_challenge(request, id):
    try:
        challenge = Challenge.objects.get(id=id, user=request.user)
        challenge.delete()
        messages.success(request, "Challenge removed successfully")
        return redirect("challenges")
    except Challenge.DoesNotExist:
        messages.error(request, "Challenge not found")
        return redirect("challenges")
    except Exception:
        messages.error(request, "Error removing challenge")
        return redirect("challenges")


@login_required(login_url="sign_in")
def report(request, challenge_id):
    try:
        challenge = Challenge.objects.get(id=challenge_id, user=request.user)

        flashcards = ChallengeFlashcard.objects.filter(challenge=challenge)
        answered_flashcards = flashcards.filter(is_answered=True)
        not_answered_flashcards = flashcards.filter(is_answered=False).count()
        correct = answered_flashcards.filter(is_correct=True).count()
        incorrect = answered_flashcards.filter(is_correct=False).count()
        data = [correct, incorrect, not_answered_flashcards]

        categories = challenge.categories.all()
        category_names = [category.name for category in categories]
        data2 = [flashcards.filter(flashcard__category=category, is_correct=True).count() for category in categories]
        data2_incorrect = [
            answered_flashcards.filter(flashcard__category=category, is_correct=False).count()
            for category in categories
        ]

        def category_object(category):
            index = category_names.index(category.name)
            return {
                "name": category.name,
                "correct": data2[index],
                "incorrect": data2_incorrect[index],
            }

        worst_categories = [
            categories[i] for i in range(len(categories)) if data2[i] == 0 or data2_incorrect[i] >= data2[i] * 0.5
        ]
        best_categories = [category_object(category) for category in categories if category not in worst_categories]
        worst_categories = [category_object(category) for category in worst_categories]

        return render(
            request,
            "report.html",
            {
                "challenge": challenge,
                "data": data,
                "data2": data2,
                "category_names": category_names,
                "worst_categories": worst_categories,
                "best_categories": best_categories,
            },
        )
    except Challenge.DoesNotExist:
        messages.error(request, "Challenge not found")
        return redirect("challenge", id=challenge_id)
    except Exception:
        messages.error(request, "Error loading challenge")
        return redirect("challenge", id=challenge_id)

async_study/challenges/templates/challenge.html
{% extends "base.html" %}
{% load static filters %}

{% block title %}{{ challenge.title }} {% endblock title %}

{% block content %}
  <div class="grid grid-rows-2 lg:grid-cols-2 size-full mt-10 max-w-7xl mx-auto px-2">
    <div class="w-full flex flex-col items-center lg:items-start">
      <h1 class="font-bold text-3xl">{{ challenge.title }}</h1>
      <div class="flex gap-1 mt-3">
        {% for category in challenge.categories.all %}
          <span class="py-1 px-3 bg-secondary/30 rounded-md text-sm">{{ category }}</span>
        {% endfor %}
        <span
          class="py-1 px-3 rounded-md text-sm {% if challenge.difficulty == 'E' %}bg-green-600/60{% elif challenge.difficulty == 'M' %}bg-yellow-600/60{% else %}bg-red-600/60{% endif %}"
        >
          {{ challenge.get_difficulty_display }}
        </span>
      </div>
      <div class="flex flex-col gap-4 w-full mt-8 items-center lg:items-stretch">
        {% if not flashcards %}
          <p class="text-lg">No flashcard found</p>
        {% else %}
          {% for f in flashcards %}
            {% include "partials/flashcard.html" with f=f challenge_flashcard=True %}
          {% endfor %}
        {% endif %}
      </div>
    </div>
    <div class="w-full flex flex-col items-center lg:items-start mt-20 lg:mt-0">
      <h2 class="font-bold text-2xl">Result</h2>
      <div class="flex flex-col gap-2 mt-6">
        <p class="text-lg">Correct: {{ correct }}</p>
        <p class="text-lg">Incorrect: {{ incorrect }}</p>
        <p class="text-lg">Not answered: {{ not_answered_flashcards }}</p>
      </div>
      <div class="flex gap-2 justify-center flex-wrap my-10">
        <a href="{% url "report" challenge.id %}" class="button-primary">Detailed report</a>
        <a
          href="{% url "remove_challenge" challenge.id %}"
          class="button-primary"
        >
          Remove Challenge
        </a>
      </div>
    </div>
  </div>
{% endblock content %}

{% block js %}
<script src="{% static "flashcards/js/flashcards.js" %}"></script>
{% endblock js %}

async_study/challenges/templates/challenges.html
{% extends "base.html" %}
{% load static %}

{% block title %}Challenges{% endblock title %}

{% block content %}
  <div class="flex flex-col justify-center max-w-3xl mx-auto mt-16">
    <form
      method="get"
      action="{% url "challenges" %}"
      class="flex items-center gap-4 flex-col sm:flex-row px-2"
    >
      <div class="flex flex-col gap-2 w-full">
        <label for="category" class="label">Category:</label>
        <select id="category" name="category" class="input">
          <option value="">---------</option>
          {% for category in categories %}
            <option
            {% if f.category == category.id|slugify %}selected{% endif %}
              value="{{ category.id }}"
            >
              {{ category.name }}
            </option>
          {% endfor %}
        </select>
      </div>
      <div class="flex flex-col gap-2 w-full">
        <label for="difficulty" class="label">Difficulty:</label>
        <select id="difficulty" name="difficulty" class="input">
          <option value="">---------</option>
          {% for difficulty in difficulties %}
            <option
            {% if f.difficulty.value == difficulty.value %}selected{% endif %}
              value="{{ difficulty.value }}"
            >
              {{ difficulty.label }}
            </option>
          {% endfor %}
        </select>
      </div>
      <div class="flex flex-col gap-2 w-full">
        <label for="difficulty" class="label">Status:</label>
        <select id="status" name="status" class="input">
          <option value="">---------</option>
          <option value="True" {% if f.status %}selected{% endif %}>Answered</option>
          <option value="False" {% if f.status == False %}selected{% endif %}>Not answered</option>
        </select>
      </div>
      <button type="submit" class="button-primary self-end">Filter</button>
    </form>
    <a href="{% url "start_challenge" %}" class="link-primary mt-6 mb-2 w-fit ml-2 md:ml-0">
      Start a challenge
    </a>
    <div class="py-1 px-2 md:p-4 border md:rounded flex flex-col gap-1">
      <div class="w-full overflow-auto pb-2 max-h-[500px] overscroll-contain">
        <table class="w-full caption-top text-sm">
          <caption class="mb-4 text-sm text-muted-foreground">
            A list of your challenges.
          </caption>
          <thead class="[&_tr]:border-b">
            <tr class="border-b duration-200 hover:bg-muted/50">
              <th class="h-12 px-4 text-left align-middle font-medium text-muted-foreground">Challenge</th>
              <th class="h-12 px-4 text-left align-middle font-medium text-muted-foreground">Title</th>
              <th class="h-12 px-4 text-left align-middle font-medium text-muted-foreground">Difficulty</th>
              <th class="h-12 px-4 text-left align-middle font-medium text-muted-foreground">Status</th>
            </tr>
          </thead>
          <tbody class="[&_tr:last-child]:border-0">
            {% for challenge in challenges %}
              <tr class="border-b duration-200 hover:bg-muted/50 focus-within:bg-muted/50">
                <td class="p-4 align-middle font-medium">
                  <a href="{% url "challenge" challenge.id %}" class="link">#{{ challenge.id }}</a>
                </td>
                <td class="p-4 align-middle font-medium">
                  <a href="{% url "challenge" challenge.id %}" class="link">{{ challenge.title }}</a>
                  </td>
                <td class="p-4 align-middle font-medium">
                  <span class="px-2 py-0.5 rounded-lg {% if challenge.difficulty == 'E' %}bg-green-600{% elif challenge.difficulty == 'M' %}bg-yellow-600{% else %}bg-red-600{% endif %}">
                    {{ challenge.get_difficulty_display }}
                  </span>
                </td>
                <td class="p-4 align-middle font-medium truncate">
                  <span class="px-2 py-0.5 rounded-lg {% if challenge.is_answered %}bg-green-600{% else %}bg-blue-600{% endif %}">
                    {% if challenge.is_answered %}Answered{% else %}Not answered{% endif %}
                  </span>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}

async_study/challenges/templates/report.html
{% extends "base.html" %}
{% load static filters %}

{% block title %}{{ challenge.title }} - Report{% endblock title %}

{% block content %}
  <div class="flex flex-col mt-10 max-w-7xl mx-auto px-2 relative">
    <div class="w-full flex flex-col items-center lg:items-start border-b pb-8">
      <a href="{% url "challenge" challenge.id %}" class="link">
        <h1 class="font-bold text-3xl">{{ challenge.title }}</h1>
      </a>
      <div class="flex flex-wrap justify-center gap-1 mt-3">
        {% for category in challenge.categories.all %}
          <span class="py-1 px-3 bg-secondary/30 rounded-md text-sm">{{ category }}</span>
        {% endfor %}
        <span
          class="py-1 px-3 rounded-md text-sm {% if challenge.difficulty == 'E' %}bg-green-600/60{% elif challenge.difficulty == 'M' %}bg-yellow-600/60{% else %}bg-red-600/60{% endif %}"
        >
          {{ challenge.get_difficulty_display }}
        </span>
      </div>
    </div>
    <div class="flex flex-col md:flex-row gap-8 md:gap-0 mt-10 pb-10 border-b">
      <div class="flex flex-col gap-5 w-full">
        <h2 class="text-2xl font-bold">Total hits</h2>
        <canvas id="graph1"></canvas>
      </div>
      <div class="flex flex-col gap-5 w-full">
        <h2 class="text-2xl font-bold">Hits by area of knowledge</h2>
        <canvas id="graph2"></canvas>
      </div>
    </div>
    <div class="flex flex-col gap-6 my-10">
      <div class="flex flex-col gap-3 w-full">
        <h2 class="text-2xl font-bold">Best categories</h2>
        <div class="flex gap-6">
          {% for category in best_categories %}
            <div class="bg-secondary/40 rounded-md flex flex-col">
              <div class="w-full h-10 bg-secondary py-2 px-3 rounded-t-md">
                <span class="text-lg">{{ category.name }}</span>
              </div>
              <div class="flex flex-col p-3">
                <p class="text-lg">Correct: {{ category.correct }}</p>
                <p class="text-lg">Incorrect: {{ category.incorrect }}</p>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
      <div class="flex flex-col gap-3 w-full">
        <h2 class="text-2xl font-bold">Worst categories</h2>
        <div class="flex gap-6">
          {% for category in worst_categories %}
            <div class="bg-secondary/40 rounded-md flex flex-col">
              <div class="w-full h-10 bg-secondary py-2 px-3 rounded-t-md">
                <span class="text-lg">{{ category.name }}</span>
              </div>
              <div class="flex flex-col p-3">
                <p class="text-lg">Correct: {{ category.correct }}</p>
                <p class="text-lg">Incorrect: {{ category.incorrect }}</p>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block js %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{% static "challenges/js/graph.js" %}"></script>
<script>createGraphs({{ data }}, {{ data2 }}, {{ category_names|safe }})</script>
{% endblock js %}

async_study/challenges/templates/start_challenge.html
{% extends "base.html" %}
{% load static %}

{% block title %}Start Challenge{% endblock title %}

{% block content %}
  <div class="flex flex-col justify-center items-center mt-16 px-4">
    <h1 class="text-5xl font-bold text-center">Start Challenge</h1>
    <h3 class="text-2xl font-medium mt-4 text-center">
      Create a challenge and choose the category and difficulty
    </h3>
    <form
      method="post"
      action="{% url "start_challenge" %}"
      class="flex flex-col gap-2 sm:gap-4 mt-10 w-full max-w-[600px]"
    >
      {% csrf_token %}
      <div class="flex flex-col gap-2 w-full">
        <label for="title" class="label text-lg">Challenge title:</label>
        <input
          type="text"
          id="title"
          name="title"
          class="input"
          placeholder="My challenge..."
          required
        />
      </div>
      <div class="flex flex-col gap-2 w-full">
        <label for="questions_qt" class="label text-lg">Questions quantity:</label>
        <input type="number" id="questions_qt" name="questions_qt" class="input" value="1" required />
      </div>
      <div class="flex flex-col md:flex-row gap-4">
        <div class="flex flex-col gap-2 w-full">
          <label for="categories" class="label text-lg">Categories:</label>
          <select id="categories" name="categories" class="input h-28" required multiple>
            {% for category in categories %}
              <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="flex flex-col gap-2 w-full">
          <label for="difficulty" class="label text-lg">Difficulty:</label>
          <select id="difficulty" name="difficulty" class="input" required>
            {% for difficulty in difficulties %}
              <option value="{{ difficulty.value }}">{{ difficulty.label }}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <button type="submit" class="button-primary mt-10 px-8 text-lg uppercase">Start</button>
    </form>
  </div>
{% endblock content %}